services:

  livekit:
    image: livekit/livekit-server:latest
    command: --dev --bind 0.0.0.0 --node-ip=192.168.1.199
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "50000-50100:50000-50100/udp"
    environment:
      LIVEKIT_KEYS: "devkey: devsecret1234567890devsecret1234567890"

  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    restart: unless-stopped

  music-bot:
    build: ./music-bot
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      LIVEKIT_WS_URL: ws://livekit:7880
      LIVEKIT_API_KEY: devkey
      LIVEKIT_API_SECRET: devsecret1234567890devsecret1234567890

      BACKEND_URL: http://host.docker.internal:8080
      POT_PROVIDER_URL: http://pot-provider:4416
    volumes:
      - ./music-bot/data:/app/data
    depends_on:
      - livekit
      - pot-provider
